# Generated by Django 2.2.1 on 2019-05-07 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_auto_20190506_2155'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Villages',
            new_name='Village',
        ),
    ]
