# Generated by Django 2.2.1 on 2019-07-01 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0005_healthcenter'),
    ]

    operations = [
        migrations.AddField(
            model_name='mother',
            name='dueMonth',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='mother',
            name='dueYear',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
