# Generated by Django 2.2.1 on 2019-07-01 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0006_auto_20190701_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='mother',
            name='hasComplications',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
