# Generated by Django 2.2.1 on 2019-07-11 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0007_mother_hascomplications'),
    ]

    operations = [
        migrations.CreateModel(
            name='Midwife',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='people.Person')),
                ('healthcenter', models.CharField(max_length=50)),
            ],
            bases=('people.person',),
        ),
    ]
