# Generated by Django 2.2.1 on 2019-08-17 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0008_midwife'),
    ]

    operations = [
        migrations.CreateModel(
            name='MotherDriverConnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driverIsComing', models.BooleanField()),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.Driver')),
                ('mother', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.Mother')),
            ],
        ),
    ]
