# Generated by Django 2.2.1 on 2019-08-17 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0009_motherdriverconnection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='motherdriverconnection',
            name='driver',
        ),
        migrations.AddField(
            model_name='motherdriverconnection',
            name='driverPhoneNumber',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
