# Generated by Django 2.2.1 on 2019-08-17 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0011_auto_20190817_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='motherdriverconnection',
            name='motherName',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='motherdriverconnection',
            name='motherVillage',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
